[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[project]
name = "ft_package"
version = "0.0.1"
authors = [
  { name="morajaon" },
  { email="morajaon@42.fr" }
]
license = {text = "MIT"}
license-files = ["LICEN[CS]E*"]
description = "A sample test package"
readme = "README.md"
requires-python = ">=3.10"

[project.urls]
Homepage = "https://github.com/morajaon/ft_package"